#!/usr/bin/env python3
"""Install the psi wordmark and favicon into a site served from a directory.

``assets/mark/psi.json`` is the single source of truth for the mark and
``assets/mark/render_mark.py`` renders it to ``psi.svg``.  This script carries
the rendered mark into a site so the header glyph and the favicon cannot drift
from the committed assets:

* it copies ``assets/mark/psi.svg`` and ``assets/mark/psi-180.png`` (the
  180x180 Apple touch icon) into ``<site>/assets/mark/``; and
* it rewrites the wordmark between the ``<!-- mark:start ... -->`` and
  ``<!-- mark:end -->`` sentinels in ``<site>/index.html`` with the four
  ``<path>`` elements ``psi.svg`` draws, so the header inlines exactly the
  geometry of the committed mark.

Usage::

    python assets/mark/install_mark.py --site web/public
    python assets/mark/install_mark.py --site web/public --check
    python assets/mark/install_mark.py --print
    python assets/mark/install_mark.py --site <checkout> --assets-only

``--check`` copies nothing: it compares the installed files byte-for-byte with
the committed assets, the inline block with the rendered SVG, and the two
favicon ``<link>``s the head must carry, then exits non-zero when the site is
stale.

The journal site (``superposition.github.io``) is a Jekyll site.  Its layout
writes the same inline block inside ``<a class="wordmark">`` and its head uses
``{{ '/assets/mark/psi.svg' | relative_url }}`` paths, so its assets are
installed here with ``--assets-only`` against a checkout and the two layout
edits are applied by hand.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import render_mark

HERE = Path(__file__).resolve().parent
DEFAULT_SITE = HERE.parent.parent / "web" / "public"

SVG_NAME = "psi.svg"
TOUCH_ICON_NAME = "psi-180.png"
ASSETS_DIR = ("assets", "mark")

INLINE_START = "<!-- mark:start generated by assets/mark/install_mark.py -->"
INLINE_END = "<!-- mark:end -->"


def head_links() -> list:
    """The head links that point the page at the installed favicon files."""
    href = "/".join(ASSETS_DIR)
    return [
        '<link rel="icon" type="image/svg+xml" href="{}/{}">'.format(href, SVG_NAME),
        '<link rel="apple-touch-icon" href="{}/{}">'.format(href, TOUCH_ICON_NAME),
    ]


class InstallError(Exception):
    """The site cannot be installed into as described."""


def inline_mark(spec: dict) -> str:
    """Return the header ``<svg class="mark">`` block for a validated spec.

    The ``<path>`` elements are taken verbatim from ``render_mark.render``, the
    same function that writes ``psi.svg``: the SVG element is retagged with the
    site's ``mark`` class and the enclosing ``viewbox`` frame.
    """
    viewbox = render_mark.num(float(spec["viewbox"]))
    paths = [line.strip() for line in render_mark.render(spec).splitlines()
             if line.strip().startswith("<path ")]
    if not paths:
        raise InstallError("render_mark.render produced no <path> elements")
    lines = ['<svg class="mark" viewBox="0 0 {0} {0}" aria-hidden="true">'.format(viewbox)]
    lines.extend("  " + path for path in paths)
    lines.append("</svg>")
    return "\n".join(lines)


def splice_inline(text: str, inline: str) -> str:
    """Replace the sentinel-delimited region of ``text`` with ``inline``."""
    start = text.find(INLINE_START)
    end = text.find(INLINE_END)
    if start == -1 or end == -1:
        raise InstallError(
            "index.html is missing the {!r} / {!r} sentinels".format(
                INLINE_START, INLINE_END))
    if end < start:
        raise InstallError("index.html has the mark:end sentinel before mark:start")
    if text.find(INLINE_START, start + 1) != -1 or text.find(INLINE_END, end + 1) != -1:
        raise InstallError("index.html repeats a mark sentinel; expected exactly one of each")
    return text[: start + len(INLINE_START)] + "\n" + inline + "\n" + text[end:]


def _compare(installed: Path, source: Path, problems: list) -> None:
    if not installed.exists():
        problems.append("{} is missing; run the script without --check".format(installed))
        return
    if installed.read_bytes() == source.read_bytes():
        return
    problems.append("{} differs from {}".format(installed, source))


def install(site: Path, assets_only: bool, check: bool) -> int:
    if not site.is_dir():
        print("install_mark: {} is not a directory".format(site), file=sys.stderr)
        return 2

    try:
        spec = render_mark.load_spec()
    except render_mark.SpecError as exc:
        print("install_mark: invalid psi.json: {}".format(exc), file=sys.stderr)
        return 2

    inline = inline_mark(spec)
    sources = [(SVG_NAME, HERE / SVG_NAME), (TOUCH_ICON_NAME, HERE / TOUCH_ICON_NAME)]

    index = site / "index.html"
    committed = rendered = None
    if not assets_only:
        if not index.exists():
            print("install_mark: {} is missing".format(index), file=sys.stderr)
            return 2
        committed = index.read_bytes().decode("utf-8")
        try:
            rendered = splice_inline(committed, inline)
        except InstallError as exc:
            print("install_mark: {}".format(exc), file=sys.stderr)
            return 2

    if not check:
        missing = [source for _, source in sources if not source.exists()]
        if missing:
            print("install_mark: {} is missing; run "
                  "assets/mark/render_mark.py first".format(missing[0]), file=sys.stderr)
            return 2

    problems = []
    assets = site.joinpath(*ASSETS_DIR)
    if not check:
        assets.mkdir(parents=True, exist_ok=True)
        for name, source in sources:
            assets.joinpath(name).write_bytes(source.read_bytes())

    for name, source in sources:
        _compare(assets / name, source, problems)

    if not assets_only:
        if check:
            if committed != rendered:
                problems.append("{} inline mark is stale".format(index))
            for link in head_links():
                if link not in committed:
                    problems.append("{} does not link {}".format(index.name, link))
        else:
            index.write_bytes(rendered.encode("utf-8"))

    if problems:
        for problem in problems:
            print("install_mark: {}".format(problem), file=sys.stderr)
        return 1

    print("install_mark: {} {} ({} paths, {} assets)".format(
        "up to date:" if check else "wrote", site, len(inline.splitlines()) - 2, len(sources)))
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Install the psi wordmark and favicon into a site directory.")
    parser.add_argument(
        "--site", type=Path, default=DEFAULT_SITE,
        help="the site root to install into (default: {})".format(DEFAULT_SITE))
    parser.add_argument(
        "--check", action="store_true",
        help="copy nothing; exit non-zero if the site differs from the assets")
    parser.add_argument(
        "--assets-only", action="store_true",
        help="install the favicon files but leave index.html alone")
    parser.add_argument(
        "--print", dest="print_only", action="store_true",
        help="print the inline wordmark block and exit")
    args = parser.parse_args(argv)

    try:
        spec = render_mark.load_spec()
    except render_mark.SpecError as exc:
        print("install_mark: invalid psi.json: {}".format(exc), file=sys.stderr)
        return 2

    if args.print_only:
        print(inline_mark(spec))
        return 0

    return install(args.site.resolve(), args.assets_only, args.check)


if __name__ == "__main__":
    sys.exit(main())
